{{- include "chat.validate" . -}}
{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chat.componentName" (dict "ctx" . "component" "jwt") }}
  labels:
    {{- include "chat.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-access-secret: {{ .Values.secrets.jwtAccessSecret | quote }}
  jwt-refresh-secret: {{ .Values.secrets.jwtRefreshSecret | quote }}
{{- end }}
{{- if and .Values.postgresql.enabled (not .Values.postgresql.auth.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chat.componentName" (dict "ctx" . "component" "postgresql") }}
  labels:
    {{- include "chat.componentLabels" (dict "ctx" . "component" "postgresql") | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.postgresql.auth.password | quote }}
{{- end }}
